### PR TITLE
Avoid UnusedTracker creation when minimizeJar is not requested

### LINKED ISSUE #479: Avoid UnusedTracker creation
Even if a project using `shadow` doesn't configure `minimizeJar=true`, the `UnusedTracker` is instantiated. This is a) unneccessary and b) fails sometimes in multi-module projects. See #425 and related PRs: #477 and #478 (which both introduce new erros) for details on those failures.

So, what about not creating an instance of `UnusedTracker` at all when `minimize` is not requested?

The failures described in b) are _not_ touched by this issue.

### PR DESCRIPTION
**Pull request by sormuras**
Closes #479

### CODE REVIEW

**Comment by sormuras** [comment]
Ping @johnrengelman ... any plans to include this PR or implement some other measure to help with `UnusedTracker` issues?

**Comment by marcphilipp** [comment]
@johnrengelman Any chance of getting this merged? We currently have to use a fork of the plugin in junit5. https://github.com/junit-team/junit5/blob/02417272bb22b8c710a0f58bc98505a49ef82107/settings.gradle.kts#L15

**Comment by sormuras** [comment]
Any news?

**Comment by cowwoc** [comment]
@johnrengelman Please merge this.

**Comment by sormuras** [comment]
Yeah, would be great to get rid of this work-around https://github.com/junit-team/junit5/commit/c4a2a7b9a6fc497b4e2015d00068e7335eccaabb

**Comment by sormuras** [comment]
Thanks for merging, @johnrengelman!

Already updated our Gradle configuration to your latest `master` revision built on-the-fly via JitPack.

**Pull request merged**
