### PR TITLE
Upgrade to ASM 7.3.1 to support JDK 15

### PR DESCRIPTION
**Pull request by vyazelenko**
@johnrengelman Any estimate on when the next version of the Shadow plugin will be released?

### CODE REVIEW

**Comment by VoxelGod** [comment]
Unfortunately, a JDK 14 and 15 preview feature (records) requires ASM 8.
```
* What went wrong:
Execution failed for task ':shadowJar'.
> Records requires ASM8
```

**Comment by johnrengelman** [comment]
6.0.0 is using ASM 8.0.1 - https://github.com/johnrengelman/shadow/blob/master/gradle/dependencies.gradle#L8

**Comment by VoxelGod** [comment]
@johnrengelman One of my colleagues inspected the stacktrace (https://hastebin.com/egemarucaw.txt) and found ASM7 references in jdependency to be responsible:
https://github.com/tcurdt/jdependency/blob/c2e760c533225d313c5ef8e1d1f14840591bf431/src/main/java/org/vafer/jdependency/asm/DependenciesClassAdapter.java#L128

I can notify them of the issue, then jdependency would need to be updated in ShadowJar as well.

**Comment by johnrengelman** [comment]
Looks like jdependency 2.4.0 uses ASM 8

**Comment by VoxelGod** [comment]
Is it possible this dependency update could be targeted for a minor release in the future? For now, I'll exclude records from my project.

**Comment by bridgettewp** [comment]
Encountering the same issue with JDK 14 preview features. Records and instanceof pattern matching throw a TaskExecutionException. Relocation and minimization do work now, though.

**Pull request merged**
